### ISSUE TITLE
Problem editing resources when using emacs

### ISSUE THREAD

**Issue by Kyrremann** [dty1er/kubecolor#2]
Get this error after I started using `kubecolor`. My editor is emacs running as daemon.

```
$ k edit deployments.apps unleash
emacsclient: could not get terminal name
emacsclient: error executing alternate editor ""
error: there was a problem with the editor "emacsclient -t"
```

**Comment by dty1er** [comment]
@Kyrremann 
Hi, can you update kubecolor to the latest (go get -u github.com/dty1er/kubecolor/cmd/kubecolor) then try again? I think I fixed the problem

**Comment by Kyrremann** [comment]
Can confirm that it works on my machine! Thanks for the help!
