### ISSUE TITLE
Installation without depending on go get

### ISSUE THREAD

**Issue by dty1er** [dty1er/kubecolor#27]
Currently kubecolor can be installed via `go get`, but ideally it should not be depending on go command. We should:
* enable kubecolor to be installed via package manager (homebrew etc)
* distribute pre-build binary via GitHub release

**Comment by rothgar** [comment]
Would you be open to a PR that adds releases based on goreleaser? If you have a homebrew-tap repo I can help make it work with github actions too.

**Comment by otherguy** [comment]
Homebrew would be much appreciated!

**Comment by dty1er** [comment]
@rothgar 

Hi, sorry for my late response 😓 I missed your comment.
I actually have never used goreleaser, but it looks good to me, I would be happy if you can send me a PR!

I am thinking to distribute kubecolor using homebrew, but I need to learn how to do that.

**Comment by rothgar** [comment]
No problem, I'll work on a PR. I'll try to send it over late next week (I'm pretty busy with Kubecon ATM)

You should probably set up a repo called `homebrew-tap` under your GitHub user. That way we can push the formula there and people can install it with `brew install dty1er/tap/kubecolor`

I'd love to get this set up so I can install it along site my tool github.com/rothgar/k

**Comment by dty1er** [comment]
@rothgar 

Thank you!
I will try to setup a repo and write Formula.
