### ISSUE TITLE
yaml color for `kubecolor apply -o yaml`

### ISSUE THREAD

**Issue by thomas-riccardi** [dty1er/kubecolor#37]
kubecolor 0.0.7: `kubecolor apply -f foo.yaml -o yaml`
Actual result: all yaml output is green.

Expected result: it would be great if the yaml output would be nicely colored like with `kubecolor get pods -o yaml`.

**Comment by dty1er** [comment]
I should do this.
The reason I did not support `apply` by kubecolor is  because I didn't know apply accepts `-o`.
Let me try to implement it...

**Comment by dty1er** [comment]
@thomas-riccardi 
Hi, I fixed this issue in [v0.0.8](https://github.com/dty1er/kubecolor/releases/tag/v0.0.8). Can you try upgrading kubecolor? 
Thank you!

**Comment by thomas-riccardi** [comment]
@dty1er I confirm it works great with v0.0.8! Thank you!

**Comment by dty1er** [comment]
Cool! Thank you for opening this issue and using kubecolor!
