### ISSUE TITLE
Can't get this working

### ISSUE THREAD

**Issue by yathishgowdaanandaraj-pge** [dty1er/kubecolor#4]
I followed the readme file and did the installation. After that the kubecolor command does not work.

**Comment by TheKas** [comment]
add ~/go/bin to your PATH in the .bashrc/.zshrc 
`echo 'export PATH="$PATH:~/go/bin"' >> ~/.bashrc`
and source it new
`source ~/.bashrc`

**Comment by yathishgowdaanandaraj-pge** [comment]
Great, that worked. Does this work with zsh terminal as well or is it only for bash ?

**Comment by denysvitali** [comment]
Works with zsh as well, just use .zshrc instead of .bashrc 👍

**Comment by dty1er** [comment]
`export PATH="$PATH:$GOPATH/bin"` might be better just in case you change your $GOPATH.

**Comment by yathishgowdaanandaraj-pge** [comment]
Wow that looks amazing it worked in bash, that's some amazing work guys. 

But I am not able to get it work with zsh, I added the the path to zshrc and sources the file it still gives me error
zsh: command not found: kubecolor

**Comment by denysvitali** [comment]
You'll also need to add GOPATH to zshrc as well, if you don't have it there (:

**Comment by denysvitali** [comment]
You'll also need to add GOPATH to zshrc as well, if you don't have it there (:

**Comment by yathishgowdaanandaraj-pge** [comment]
Yes I added both of these to the zshrc file 
export PATH="$PATH:~/go/bin"
export PATH="$PATH:$GOPATH/bin"

I still get the same error :-(

**Comment by denysvitali** [comment]
What's the output of (from zsh):

```sh
source ~/.zshrc
which kubecolor
ls -la ~/go/bin/kube*
kubecolor
```

?

**Comment by yathishgowdaanandaraj-pge** [comment]
This is what it looks like 
```
source ~/.zshrc                                         

which kubecolor                                              
kubecolor not found

ls -la ~/go/bin/kube*                                        
-rwxr-xr-x  1 YGA2  staff  2767656 Oct 12 13:51 /Users/YGA2/go/bin/kubecolor

echo $GOPATH kubecolor                                         
kubecolor

echo $PATH kubecolor                                          
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/go/bin:/bin:~/go/bin:/bin:~/go/bin:/bin kubecolor
```

**Comment by dty1er** [comment]
Hmm that's starange, kubecolor exists in `~/go/bin/` and `~/go/bin` is in $PATH but you cannot exec kubecolor...

**Comment by denysvitali** [comment]
Can you try to use the full path instead of the ~? That will be /Users/YGA2/go/bin

**Comment by yathishgowdaanandaraj-pge** [comment]
Using this is my path worked, you guys are awesome. 

Thanks a lot everyone, appreciate all your help. Must say you guys have put some amazing work.

**Comment by yagi5** [comment]
Oh nice. Let me close this issue but please feel free to reopen if you have any issues. Enjoy kubecolor!

@TheKas @denysvitali 
Thank you for your support!!
