### ISSUE TITLE
Kubecolor autocompletion does not work and break canonical k alias

### ISSUE THREAD

**Issue by bygui86** [dty1er/kubecolor#44]
I tried to enable the autocompletion for kubecolor following instructions on the official README:

> Basically, configuring autocompletion for kubecolor requires adding following line in your shell config file.
> ```bash
> # autocomplete for kubecolor
> complete -o default -F __start_kubectl kubecolor
> ```
> If you are using an alias like k="kubecolor", then just change above like:
> ```bash
> complete -o default -F __start_kubectl k
> ```

but it does not work, no autocompletion for kubecolor and even worse no autocompletion anymore for `k` alias!

Here some info:
- OS: macos catalina v10.15.7
- kubectl: official v1.20.2
- `k` alias set and autocompletion properly working (without enabling kubecolor autocompletion)

Here the output of `kubectl version` command:
```bash
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:14:17Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
```

Any help is really appreciated!!

**Comment by ecsecta** [comment]
Have a look here, works for my zsh setup: https://github.com/dty1er/kubecolor/issues/32#issuecomment-724411738

**Comment by bygui86** [comment]
Thanks @ecsecta ! I will try asap

**Comment by bygui86** [comment]
@ecsecta  the solution you proposed does not work.

```shell script
source <(kubectl completion zsh)
alias kubectl="kubecolor"
compdef kubecolor="kubectl"
```

with `complete -o default -F __start_kubectl kubectl` **commented**

I forgot to mention:
- zsh version: 5.8 (x86_64-apple-darwin19.6.0)
- kubecolor installed via `brew`

**Comment by dty1er** [comment]
@bygui86 
Can you show me the whole .zshrc?
On my environment this works:

```
source <(kubectl completion zsh)
alias kubectl="kubecolor"
compdef kubecolor="kubectl"
```

**Comment by bygui86** [comment]
@dty1er I could but it would be pretty difficult to read... as I work on many different technologies everyday and I use tons of tools, I organised .zshrc in multiple subfiles to keep everything tidy.

Here an example of the .zshrc structure:

```bash
source configs.sh

source oh-my-zsh.zsh

source env-vars.sh

source ps1-prompt.sh

source functions.sh

source path.sh

source aliases.sh

source company_configs.sh

source autocompletion.sh
```

I tried both following ways (commenting everything else related to kubectl and k):

```bash
# ...

source <(kubectl completion zsh)
alias kubectl="kubecolor"
compdef kubecolor="kubectl"

# ...
```

```bash
### load all aliases together
# some aliases (e.g. ll, ...)
alias kubectl="kubecolor"
compdef kubecolor="kubectl"
# some other aliases (e.g. gcloud, kubectx, kubens, ...)

### source all autocompletion together
# source some autocompletion (e.g. brew, ...)
source <(kubectl completion zsh)
# source some other autocompletion (e.g. gcloud, helm, ...)
```

but still it doesn't work.

I will try excluding everything and loading only your 3 lines, let's see...

**Comment by bygui86** [comment]
I tried with a super minimal .zshrc:

```bash
#!/bin/zsh

source "$HOME/oh-my-zsh.zsh"

source <(kubectl completion zsh)
alias kubectl="kubecolor"
compdef kubecolor="kubectl"
```

and it worked!

Now I have to guess which of my other scripts creates this issue :(

@dty1er any known conflict between kubecolor and other tools? for example gcloud, krew, kubectx, kubens or similar?

**Comment by dty1er** [comment]
@bygui86 
I see.
Unfortunately, I currently don't know any tools which make the completion not working. I guess you can investigate it by bisecting your .zshrc.
If you can find which part was causing this problem, I'd like you to report it here. The information should be much helpful for other people, so I want to consider writing it in this project README.

**Comment by bygui86** [comment]
@dty1er I found the conflict:

```bash
if type brew &>/dev/null; then
	FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
	autoload -Uz compinit
	compinit
fi
```

I use these lines to load `zsh-completions`.

Everything depends on the order...

WORKS
```bash
#!/bin/zsh

if type brew &>/dev/null; then
	FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
	autoload -Uz compinit
	compinit
fi

source "$HOME/oh-my-zsh.zsh"

source <(kubectl completion zsh)
alias kubectl="kubecolor"
compdef kubecolor="kubectl"
```


DOES NOT WORK
```bash
#!/bin/zsh

source "$HOME/oh-my-zsh.zsh"

source <(kubectl completion zsh)
alias kubectl="kubecolor"
compdef kubecolor="kubectl"

if type brew &>/dev/null; then
	FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
	autoload -Uz compinit
	compinit
fi
```

No matter other aliases, functions or autocompletions loaded before or after...

**Comment by dty1er** [comment]
@bygui86 

Thank you for your effort!
I don't understand how zsh completion works deeply, but it seems like compinit should be located before compdef? I could find [something similar](https://stackoverflow.com/a/60383091/13914809), but I'm still not sure.

Anyway, I'm happy to hear it worked on your environment.
Let me close this issue for now, but please feel free to reopen or open another one when you found something else.
Thank you for using kubecolor!
