### ISSUE TITLE
kubectl run command showing disorder outputs

### ISSUE THREAD

**Issue by manfredliuactive** [dty1er/kubecolor#46]
I'm running kubectl run -i --tty busybox --image=busybox --restart=Never -- sh.  the shell would not echo any character inputed. 
after entering enter, the commands are executed but the output is not readable. 

```
If you don't see a command prompt, try pressing enter.

                                                      / #
                                                          / # ls
                                                                bin   dev   etc   home  proc  root  sys   tmp   usr   var

```

**Comment by dty1er** [comment]
Nice catch, it reproduced.

**Comment by dty1er** [comment]
@manfredliuactive 
Hi, can you update kubecolor to the latest and try again?
You can update it by `brew upgrade` or `go get -u`.

**Comment by dty1er** [comment]
I'll close this but feel free to reopen if needed.
