### ISSUE TITLE
Want to always run with --light-background

### ISSUE THREAD

**Issue by demshin** [dty1er/kubecolor#49]
Hello!
Thanks for very useful tool.

I'm using kubecolor on macos with zsh, iTerm2 with ligth theme (Solarized Light). And I want to configure kubecolor to always use `--light-background`.

Regards :)

**Comment by dty1er** [comment]
@demshin 

Hi, thank you for opening this issue.
To always use `--light-background`, you can use zsh alias feature.
You can write below line in your `.zshrc`:

```
alias kubecolor="kubecolor --light-background"
```

Then, load `~/.zshrc` by running `source ~/.zshrc` . You will now get `kubecolor --light-background` result by just running `kubecolor` .

**Comment by demshin** [comment]
It works. Thanks.

**Comment by dty1er** [comment]
Cool, let me close this issue now!
