### ISSUE TITLE
colorizing kubectl apply

### ISSUE THREAD

**Issue by perbu** [dty1er/kubecolor#56]
Hi!

This looks like a nice and useful project. I like colors. I switched from curl to httpie because colors.

Would you be interested in me attempting to colorize kubectl apply? Currently it is all green. I'd like it to be mostly white, with separate colors for actions that are "unchanged", "created", "configured", etc. 

I've not looked at the code so I don't know if it fits. Let me know. Any other tips for an implementation would be welcome. 

Cheers
Per.

**Comment by dty1er** [comment]
@perbu 
 
Can you provide a specific example output of `kubectl apply` which you want to colorize?

**Comment by perbu** [comment]
Just colorizing "unchanged", "created", "configured". I have about 80 lines of output from my kubectl apply and I wanna highlight what is actually being changed.

**Comment by dty1er** [comment]
@perbu 

Hi, as this suggestion sounds interesting to me, I quickly tried to implement it in https://github.com/dty1er/kubecolor/pull/60.
Do you think you can try it with your environment and tell me how it looks?

Right now I'm thinking if we should leave `deployment.apps/foo` just white or not.

**Comment by perbu** [comment]
haha. Thanks!

Since I'm not planning on deploying right now I ran a dry-run and then the colors won't apply. So I think the parser might need a tiny bit more work if you wanna cover dry-runs. 

![bilde](https://user-images.githubusercontent.com/232665/116246386-3d322300-a76a-11eb-80d0-1faf5b2204f4.png)

**Comment by dty1er** [comment]
Ah cool, I updated the PR and now it should handle dry run cases.

**Comment by perbu** [comment]
Perfect.

Not sure if I should close the issue or whatever, but I'm certain all my needs have been met. 🥇

**Comment by dty1er** [comment]
I merged the PR and made a release v0.0.16 includes this change. Please update kubecolor and try again.

Thank you for the suggestion! If you have anything else please feel free to reopen or open new one.
