### ISSUE TITLE
`brew install dty1er/tap/kubecolor` fails – invalid syntax in tap!

### ISSUE THREAD

**Issue by awinecki** [dty1er/kubecolor#63]
Hey there, I'm setting up a new machine and `kubecolor` brew installation failed for me:

<img width="868" alt="CleanShot 2021-05-02 at 23 04 19@2x" src="https://user-images.githubusercontent.com/656694/116827722-d31ae300-ab9a-11eb-9bcd-32252ac6ea21.png">

My env:
- fish shell
- M1 macbook pro 13"
- Homebrew 3.1.5

**Comment by dty1er** [comment]
@awinecki 

Hi, thank you for the report! I guess this error happens on M1 mac and I applied fix for that. However, I don't have M1 mac so I cannot make sure it is fixed now. Can you try again and let me know if it still happens?

**Comment by dty1er** [comment]
Closing now...
