### ISSUE TITLE
kubecolor plugins version failed

### ISSUE THREAD

**Issue by tuxtof** [dty1er/kubecolor#68]
when i try to use the version command of a kubectl plugin it failed
ex with cert-manager

  - Screenshot of "kubectl" output
kubectl cert-manager version
util.Version{GitVersion:"v1.0.1", GitCommit:"c06d7a55dafb1a812321bf3c2ab982daa7b3e699", GitTreeState:"clean", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}

  - Screenshot of "kubecolor" output
kubecolor cert-manager version
panic: runtime error: index out of range [1] with length 1

goroutine 18 [running]:
github.com/dty1er/kubecolor/printer.(*VersionPrinter).Print(0xc00008c008, 0x11383f8, 0xc00010e028, 0x1138418, 0xc00010e008)
	/home/runner/work/kubecolor/kubecolor/printer/kubectl_version.go:41 +0xcf6
github.com/dty1er/kubecolor/printer.(*KubectlOutputColoredPrinter).Print(0xc0001161d0, 0x11383f8, 0xc00010e028, 0x1138418, 0xc00010e008)
	/home/runner/work/kubecolor/kubecolor/printer/kubectl_output_colored_printer.go:110 +0x16e
github.com/dty1er/kubecolor/command.Run.func1(0xc00013c060, 0x1138868, 0xc00010e028, 0xc00010c040)
	/home/runner/work/kubecolor/kubecolor/command/runner.go:95 +0x9b
created by github.com/dty1er/kubecolor/command.Run
	/home/runner/work/kubecolor/kubecolor/command/runner.go:94 +0x45f

  - What's the issue and what you expect

i expect to ahve the version as kubectl return

  - Shell info (bash/zsh/fish etc, its version)
zsh 5.8
kubectl v1.21.0
kubecolor 0.0.19

**Comment by dty1er** [comment]
Thank you for opening the issue! I applied workaround and the panic won't happen, can you try again.

**Comment by tuxtof** [comment]
Perfect problem solved

Thanks @dty1er
